### ISSUE TITLE
Implement a :Spline (Dierckx.jl) Kernal for Two-Stage Method

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqParamEstim.jl#10]
Another interesting setup would be to use Dierckx.jl to calculate `estimated_solution` and `estimated_derivative`. The rest of the algorithm would just work. Curious if the higher order of the spline matters here, and whether there's a performance tradeoff at all.

**Comment by Ayush-iitkgp** [comment]
Dierckx.jl only suport 1-d and 2-d splines as stated on their [github page](https://github.com/kbarbary/Dierckx.jl). Therefore, it will be not a great idea to implement it for specific ODEs.
