### ISSUE TITLE
lorenz_true_test.jl no longer runs (for me) and uses @ode_def_nohes

### ISSUE THREAD

**Issue by freemin7** [JuliaDiffEq/DiffEqParamEstim.jl#111]
Hello

i tried to execute lorenz_true_test.jl and by the point i come to:
```
g1 = @ode_def_nohes LorenzExample begin
  dx = σ*(y-x)
  dy = x*(ρ-z) - y
  dz = x*y - β*z
end σ=>10.0 ρ=>28.0 β=>2.6666
```
It fails with:
 ```
LoadError: UndefVarError: @ode_def_nohes not defined 
```
Furthermore and indepdent of this problem `@ode_def_nohes`  seems to be deprecated. See: https://github.com/JuliaDiffEq/DiffEqDocs.jl/issues/192

**Comment by ChrisRackauckas** [comment]
Handled by https://github.com/JuliaDiffEq/DiffEqParamEstim.jl/commit/74c932c7eedecf1e9f942a79a7f92cb9cae79349
