### ISSUE TITLE
Test with Evolutionary.jl

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqParamEstim.jl#12]
https://github.com/wildart/Evolutionary.jl

This is a set of evolutionary and genetic algorithms. It would be good to make sure we're compatible.

**Comment by Ayush-iitkgp** [comment]
#25 my bad I opened a similar issue. The new PR adds test for GA.

**Comment by ChrisRackauckas** [comment]
#28
