### ISSUE TITLE
Simplifications in lorenz_true_test

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqParamEstim.jl#18]
There is a glitch in:

+obj = build_loss_objective(prob_short,Tsit5(),L2Loss(t_short,data),reltol=1e-9) line 135

should read:

+obj = build_loss_objective(prob,Tsit5(),L2Loss(t,data),reltol=1e-9)

I think.....

**Comment by ChrisRackauckas** [comment]
Indeed. Would you mind doing a PR?

**Comment by finmod** [comment]
Be patient with me. Can you take me through my first PR?

**Comment by ChrisRackauckas** [comment]
Yup for sure. Take your time. If you go to the code, like here:

https://github.com/JuliaDiffEq/DiffEqParamEstim.jl/blob/master/test/lorenz_true_test.jl

There's a pencil icon on the top right. If you click on that, it goes to edit mode. You make the changes to the code, and then scroll to the bottom where you add a commit message. There you add a message, and tell it to open a PR. I think you have to hit the green button twice. Then it will open the PR, I will review it and merge it in. Then the change is credited to you.

I also put out a (really bad) video for how to do this without the web interface. Not using the web interface is obviously much more powerful, but it's overkill for these small changes. Anyways, for larger changes, this is an easy way to do it:

https://www.youtube.com/watch?v=tx8DRc7_c9I&t=82s
