### ISSUE TITLE
Solver problem with lorenz_true_test

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqParamEstim.jl#20]
Trying to refine lorenz test, I have modified the two tspans of the problem in two directions to match PODES and the Xiang2015 paper:

g1 = @ode_def_nohes LorenzExample begin
  dx = σ*(y-x)
  dy = x*(ρ-z) - y
  dz = x*y - β*z
end σ=>10.0 ρ=>28.0 β=>2.6666 # Parameters used to construct the dataset

r0 = [0,1, 0.0, 0.0]  #[-11.8,-5.1,37.5] PODES Initial values of the system in space
tspan = (0.0, 30.0) # PODES sample of 500 observations over the (0,30) timespan
prob = ODEProblem(g1, r0, tspan)
tspan2 = (0.0, 3.0) # Xiang test sample of 300 observations with a timestep of 0.01
prob_short = ODEProblem(g1, r0, tspan2)

Generating t and t_short as follows:

dt = 30.0/500                    
tf = 30.0
tinterval = 0:dt:tf
t  = collect(tinterval)

h = 0.01
M = 300
tstart = 0.0
tstop = tstart + M * h
tinterval_short = 0:h:tstop
t_short = collect(tinterval_short)

The next step produces the weird result that the time index is empty. This is running on DiffEqParamEstim master reflecting yesterday's modifications.

data_sol_short = solve(prob_short,Vern7(),saveat=t_short,reltol=1e-12,abstol=1e-12)
data_short = vecarr_to_arr(data_sol_short)
data_sol = solve(prob,Vern7(),saveat=t,reltol=1e-12,abstol=1e-12)
data = vecarr_to_arr(data_sol)

Out:
4×501 Array{Float64,2}:
 0.0  0.513358   1.17379   2.41387    4.86363  …   4.06328   6.0531   8.97193
 1.0  1.37463    2.62475   5.26597   10.4554       6.70412  10.1206  14.5554 
 0.0  0.0176899  0.107004  0.475555   1.96415     15.0128   15.1452  18.0884 
 0.0  0.0        0.0       0.0        0.0          0.0       0.0      0.0    

Then plotting impossible.

**Comment by ChrisRackauckas** [comment]
```julia
g1 = @ode_def_nohes LorenzExample begin
  dx = σ*(y-x)
  dy = x*(ρ-z) - y
  dz = x*y - β*z
end σ=>10.0 ρ=>28.0 β=>2.6666 # Parameters used to construct the dataset
```

You wrote `xy`, which Julia (and then the macro) parses as a different variable. You can only do `2y` etc. meaning only when it's actually a number literal. If it's not a constant value in front, the parser won't know what it's supposed to be two separate variables, since `xy` is a valid variable name. For example:

```julia
const xy = 2
g1 = @ode_def_nohes LorenzExample begin
dx = σ*(y-x)
dy = x*(ρ-z) - y
dz = xy - βz
end σ=>10.0 ρ=>28.0 β=>2.6666 # Parameters used to construct the dataset
```

is valid Julia, but definitely not what you meant.

So the true error was a parsing error (once again...) in the macro. This was easy to find since calling the solver:

```julia
data_sol_short = solve(prob_short,Vern7(),saveat=t_short,reltol=1e-12,abstol=1e-12)
```

gives the error:

```julia
UndefVarError: xy not defined
macro expansion at test.jl:6 [inlined]
(::LorenzExample)(::Float64, ::Array{Float64,1}, ::Array{Float64,1}) at ode_def_opts.jl:232
ode_determine_initdt(::Array{Float64,1}, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Di
::DiffEqBase.#ODE_DEFAULT_NORM, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,LorenzExample,Void,UniformScaling{Int64}}, ::Int64) at initdt.jl:6
#init#88(::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Void, ::Bool, ::Void, ::Bool, ::Bool, ::Bool, ::Float64, ::Bool, ::Rational{Int64}, ::Float64, ::Float64, ::Int64, ::Rational{Int64}, ::Rational{Int64}, ::Bool, ::Rational{Int64}, ::Rational{Int64}, ::Int64, ::Float64, ::Float64, ::DiffEqBase.#ODE_DEFAULT_NORM, ::DiffEqBase.#ODE_DEFAULT_ISOUTOFDOMAIN, ::DiffEqBase.#ODE_DEFAULT_UNSTABLE_CHECK, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Int64, ::String, ::DiffEqBase.#ODE_DEFAULT_PROG_MESSAGE, ::Void, ::Void, ::Bool, ::Bool, ::Array{Any,1}, ::DiffEqBase.#init, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,LorenzExample,Void,UniformScaling{Int64}}, ::OrdinaryDiffEq.Vern7, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at solve.jl:140
(::DiffEqBase.#kw##init)(::Array{Any,1}, ::DiffEqBase.#init, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,LorenzExample,Void,UniformScaling{Int64}}, ::OrdinaryDiffEq.Vern7, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at <missing>:0
#solve#87(::Array{Any,1}, ::Function, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,LorenzExample,Void,UniformScaling{Int64}}, ::OrdinaryDiffEq.Vern7, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at solve.jl:6
(::DiffEqBase.#kw##solve)(::Array{Any,1}, ::DiffEqBase.#solve, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,LorenzExample,Void,UniformScaling{Int64}}, ::OrdinaryDiffEq.Vern7, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at <missing>:0
(::DiffEqBase.#kw##solve)(::Array{Any,1}, ::DiffEqBase.#solve, ::DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,LorenzExample,Void,UniformScaling{Int64}}, ::OrdinaryDiffEq.Vern7) at <missing>:0
include_string(::String, ::String) at loading.jl:498
include_string(::String, ::String, ::Int64) at eval.jl:30
include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N} where N) at eval.jl:34
(::Atom.##49#52{String,Int64,String})() at eval.jl:50
withpath(::Atom.##49#52{String,Int64,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
macro expansion at eval.jl:49 [inlined]
(::Atom.##48#51{Dict{String,Any}})() at task.jl:80
```

and led me to the appropriate line number.

**Comment by ChrisRackauckas** [comment]
FWIW, I usually try to avoid the "supershorthands" `2x` and `2.` for these subtle parsing issues. This stuff is nice to use in Julia once you get the hang of it, but being explicit can pay off.

**Comment by finmod** [comment]
No. This is not it at all. The xy issue is just in the cut and paste of the Markdown code.
Actually, ln[3] is:

g1 = @ode_def_nohes LorenzExample begin
  dx = σ*(y-x)
  dy = x*(ρ-z) - y
  dz = x*y - β*z
end σ=>10.0 ρ=>28.0 β=>2.6666 # Parameters used to construct the dataset

r0 = [0,1, 0.0, 0.0]  #[-11.8,-5.1,37.5] PODES Initial values of the system in space
tspan = (0.0, 30.0) # PODES sample of 500 observations over the (0,30) timespan
prob = ODEProblem(g1, r0, tspan)
tspan2 = (0.0, 3.0) # Xiang test sample of 300 observations with a timestep of 0.01
prob_short = ODEProblem(g1, r0, tspan2)
g1 = @ode_def_nohes LorenzExample begin
  dx = σ*(y-x)
  dy = x*(ρ-z) - y
  dz = x*y - β*z
end σ=>10.0 ρ=>28.0 β=>2.6666 # Parameters used to construct the dataset
​
r0 = [0,1, 0.0, 0.0]  #[-11.8,-5.1,37.5] PODES Initial values of the system in space
tspan = (0.0, 30.0) # PODES sample of 500 observations over the (0,30) timespan
prob = ODEProblem(g1, r0, tspan)
tspan2 = (0.0, 3.0) # Xiang test sample of 300 observations with a timestep of 0.01
prob_short = ODEProblem(g1, r0, tspan2)

and out[3] is:
DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,LorenzExample,Void,UniformScaling{Int64}}(LorenzExample,[0.0,1.0,0.0,0.0],(0.0,3.0),nothing,UniformScaling{Int64}
1*I)

The rest of the error with data_sol_short as before. If you use these values in your lorenz_true_test it should reproduce this error.

**Comment by ChrisRackauckas** [comment]
Your initial condition is a length 4 vector:

```julia
r0 = [0,1, 0.0, 0.0] 
```

Are you sure that's what you want? Not something like

```julia
r0 = [1.0, 0.0, 0.0] 
```

?

**Comment by ChrisRackauckas** [comment]
with that the plots look just fine:

```julia
using Plots
plot(data_sol,vars=(1,2,3))
```

![newplot](https://cloud.githubusercontent.com/assets/1814174/26259554/60ea78e8-3c7e-11e7-9dbd-b3ba8a6047f1.png)

Of course, it's showing the interpolation is turned off because we are using `saveat`.

```julia
interpolation_sol = solve(prob,Vern7(),saveat=t,reltol=1e-12,abstol=1e-12)
plot(data_sol,vars=(1,2,3))
```

![newplot 1](https://cloud.githubusercontent.com/assets/1814174/26259608/98416a68-3c7e-11e7-8538-af60f3af9b24.png)

**Comment by finmod** [comment]
Correct. Well spotted. It was there: DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,LorenzExample,Void,UniformScaling{Int64}}(LorenzExample,[0.0,1.0,0.0,0.0],(0.0,3.0),nothing,UniformScaling{Int64}
1*I) but I did not see it. Thank you.
