### ISSUE TITLE
Implement a Multiple Shooting version of the objective function

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqParamEstim.jl#22]
http://jeti.uni-freiburg.de/papers/04140671.pdf

The paper does actually make some odd (weirdly wrong) claims, but in general it's fine. Multiple shooting is usually seen in BVPs, and it is more robust. It makes it pretty trivial to parallelize, and would just result in adding a few constraints to the objective function. So this would be most useful on MPB since Optim doesn't have constrained optimization yet.

**Comment by finmod** [comment]
@ChrisRackauckas A modern and clearer version of this paper is http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005331 and the multiple shooting is implemented in PESTO, a MATLAB package. https://github.com/ICB-DCM/PESTO.

JuliaDiffEq vision is to implement these things in Julia where most of the modules like CODVES, Sundials and more are already available. The optimization problem (5) should be available in build_loss_objective as a standard problem on which to apply various directions of investigation.

**Comment by ChrisRackauckas** [comment]
That paper is missing autodifferencing which should be much better than finite differencing yet not be as complicated as sensitivity analysis. However, DiffEq-wide adjoint sensitivities are on the docket for DiffEqSensitivity.jl. Right now, it only has forward sensitivity analysis, and Sundials CVODES has adjoint sensitivity built in, but the DiffEqSensitivity-style would allow it to be used with all ODE solvers. That will be a nice future, but its not going to be ready for awhile.

Let's keep this discussion to multiple shooting though.

**Comment by finmod** [comment]
Multiple shooting is available with BlackBoxOptim that we know well.

**Comment by ChrisRackauckas** [comment]
>Multiple shooting is available with BlackBoxOptim that we know well.

It is?

**Comment by finmod** [comment]
Sorry no, it is multiple objective optimization that is available. 

For a xBraid wrapper in Julia, there is : https://github.com/jgoldfar/XBraid.jl

**Comment by ChrisRackauckas** [comment]
Multiple shooting does two things:

1) Builds a similar cost function. Trivial.
2) Adds bounds constraints on the different time intervals. This leads to constraints for the optimization.

Thus `multiple_shooting_objective` would have to spit out not just an objective function to send to optimizers, but also a function for the equality constraints. I know how to do this with NLopt.jl, but we need to make sure that how we do it is cross package compatible, though we can start with just NLopt.jl because our tests have pretty clearly shown that it's likely the most efficient/useful right now (though we should really get IPOPT.jl a try).

**Comment by Ayush-iitkgp** [comment]
My summary of the multiple shooting research paper:
1. Divide the time into n_ms subintervals.
2. Assume the different initial values at each subinterval, solve it in terms of parameter p and initial value, find the L2-norm for each sub-interval.
3. Sum the L2 loss for each subinterval.
4. Impose the equality constraints at the boundary of the sub-intervals.
That means we have unknowns as parameters and initial values at each interval.

**Comment by Ayush-iitkgp** [comment]
How do we decide the no. of intervals?
I think the user should provide the vector of timestamps where they want to split the time domain.

**Comment by ChrisRackauckas** [comment]
>I think the user should provide the vector of timestamps where they want to split the time domain.

That sounds good. Probably default to like, `linspace` with 10 points. 

>That means we have unknowns as parameters and initial values at each interval.

Can probably use a vector of vectors default arg to let the user set it, but default to just copying the initial condition to each of those points. To the user this should be treated differently from the other parameters. But then in the optimizer it's not.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/DiffEqParamEstim.jl/pull/76
