### ISSUE TITLE
Support for Genetic Algorithm to optimize the cost function

### ISSUE THREAD

**Issue by Ayush-iitkgp** [JuliaDiffEq/DiffEqParamEstim.jl#25]
[This paper](https://bmcsystbiol.biomedcentral.com/articles/10.1186/s12918-015-0219-2) suggests using heuristic techniques to find the global optima. These methods usually obtain an adequate solution in reasonable computation time, although at the price of no guarantee. The first step is to support Genetic Algorithms. Julia has the following GA libraries:
1. [Evolutionary.jl](https://github.com/wildart/Evolutionary.jl)
2. [GeneticAlgorithms.jl](https://github.com/WestleyArgentum/GeneticAlgorithms.jl)

**Comment by ChrisRackauckas** [comment]
#28
