### ISSUE TITLE
Add support for optimizing the cost function with BlackBoxOptim.jl

### ISSUE THREAD

**Issue by Ayush-iitkgp** [JuliaDiffEq/DiffEqParamEstim.jl#26]
Add support for optimizing the cost function using global optimization framework [BlackBoxOptim.jl](https://github.com/robertfeldt/BlackBoxOptim.jl)

**Comment by ChrisRackauckas** [comment]
This is already supported. It just needs tests and docs.

**Comment by finmod** [comment]
Whereas everything in DiffEqParamEstim complies with Julia v0.6, BlackBoxOptim does not yet. @robertfeldt

**Comment by ChrisRackauckas** [comment]
I don't think there's anything more to this on our end.
