### ISSUE TITLE
CostVData syntax problem in build_loss_objective

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqParamEstim.jl#27]
On Pkg.checkout("DiffEqParamEstime") there is a Julia v0.5.2 versus Julia v0.6 update warning and Pkg.test() gives errors.

Checking that CostVData and L2Dist give same result although different syntax, I get:

obj_short = build_loss_objective(prob_short,SRIW1(),CostVData(t_short,data_short;loss_func = L2Loss))
#obj_short = build_loss_objective(prob_short,SRIW1(),L2Loss(t_short,data_short))
res1 = bboptimize(obj_short;SearchRange = LooserBounds, MaxSteps = 14e3)

MethodError: no method matching DiffEqParamEstim.L2Loss{T,D}()
Closest candidates are:
  DiffEqParamEstim.L2Loss{T,D}{T,D}(::T, ::D) at C:\Users\Denis\.julia\v0.5\DiffEqParamEstim\src\cost_functions.jl:23
  DiffEqParamEstim.L2Loss{T,D}{T}(::Any) at sysimg.jl:53

 in (::DiffEqParamEstim.CostVData{Array{Float64,1},Array{Float64,2},DataType})(::DiffEqBase.RODESolution{Float64,2,Array{Array{Float64,1},1},Void,Void,Array{Float64,1},DiffEqNoiseProcess.NoiseProcess{Float64,2,Float64,Array{Float64,1},Array{Float64,1},Array{Array{Float64,1},1},DiffEqNoiseProcess.#INPLACE_WHITE_NOISE_DIST,DiffEqNoiseProcess.#INPLACE_WHITE_NOISE_BRIDGE,true,DataStructures.Stack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},ResettableStacks.ResettableStack{Tuple{Float64,Array{Float64,1},Array{Float64,1}}},DiffEqNoiseProcess.RSWM{:RSwM3,Float64}},DiffEqBase.SDEProblem{Array{Float64,1},Float64,true,Void,DiffEqBase.##160#164{DiffEqBase.SDEProblem{Array{Float64,1},Float64,true,Void,LorenzSDE,LorenzSDENoise,Void,UniformScaling{Int64},Void},Array{Float64,1},Int64},DiffEqBase.##161#165{DiffEqBase.SDEProblem{Array{Float64,1},Float64,true,Void,LorenzSDE,LorenzSDENoise,Void,UniformScaling{Int64},Void},Array{Float64,1},Int64},Void,UniformScaling{Int64},Void},StochasticDiffEq.SRIW1,StochasticDiffEq.LinearInterpolationData{Array{Array{Float64,1},1},Array{Float64,1}}}) at C:\Users\Denis\.julia\v0.5\DiffEqParamEstim\src\cost_functions.jl:13
 in (::DiffEqParamEstim.##6#10{Bool,Int64,DiffEqBase.#problem_new_parameters,Array{Any,1},DiffEqBase.SDEProblem{Array{Float64,1},Float64,true,Void,LorenzSDE,LorenzSDENoise,Void,UniformScaling{Int64},Void},StochasticDiffEq.SRIW1,DiffEqParamEstim.CostVData{Array{Float64,1},Array{Float64,2},DataType}})(::Array{Float64,1}) at C:\Users\Denis\.julia\v0.5\DiffEqParamEstim\src\build_loss_objective.jl:31
 in (::DiffEqParamEstim.DiffEqObjective{DiffEqParamEstim.##6#10{Bool,Int64,DiffEqBase.#problem_new_parameters,Array{Any,1},DiffEqBase.SDEProblem{Array{Float64,1},Float64,true,Void,LorenzSDE,LorenzSDENoise,Void,UniformScaling{Int64},Void},StochasticDiffEq.SRIW1,DiffEqParamEstim.CostVData{Array{Float64,1},Array{Float64,2},DataType}},DiffEqParamEstim.##9#13})(::Array{Float64,1}) at C:\Users\Denis\.julia\v0.5\DiffEqParamEstim\src\build_loss_objective.jl:8
 in setup_problem(::Function, ::BlackBoxOptim.DictChain{Symbol,Any}) at C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\bboptimize.jl:36
 in #bbsetup#87(::Array{Any,1}, ::Function, ::Function, ::Dict{Symbol,Any}) at C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\bboptimize.jl:86
 in (::BlackBoxOptim.#kw##bbsetup)(::Array{Any,1}, ::BlackBoxOptim.#bbsetup, ::Function, ::Dict{Symbol,Any}) at .\<missing>:0
 in #bboptimize#86(::Array{Any,1}, ::Function, ::Function, ::Dict{Symbol,Any}) at C:\Users\Denis\.julia\v0.5\BlackBoxOptim\src\bboptimize.jl:69
 in (::BlackBoxOptim.#kw##bboptimize)(::Array{Any,1}, ::BlackBoxOptim.#bboptimize, ::Function, ::Dict{Symbol,Any}) at .\<missing>:0 (repeats 2 times)

**Comment by ChrisRackauckas** [comment]
Master requires v0.6.  It probably doesn't even import on `using` for v0.5?

BTW, you probably shouldn't be optimizing an SDE directly since every solution is different. That needs to be done in Monte Carlo.

**Comment by ChrisRackauckas** [comment]
>MethodError: no method matching DiffEqParamEstim.L2Loss{T,D}()

Oh, that's not a valid LossFunctions.jl loss.
