### ISSUE TITLE
Additive noise as regularization

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqParamEstim.jl#32]
Found a neat paper:

http://www.sciencedirect.com/science/article/pii/S0025556414000510

This shows that converting the ODE to and additive noise SDE is a form of regularization. Since my research includes SDE solvers specialized to additive noise and SRA1 is a very efficient method for this, this is a very good route to take. Note the `sigma` can be related to the likelihood variances, since this is a stand-in for the error.

**Comment by Ayush-iitkgp** [comment]
This is certainly one way to go about it. The other way is using Tikhonov regularization term in the cost function. I think `MahalanobisPenalty` in [PenaltyFunctions.jl](https://github.com/JuliaML/PenaltyFunctions.jl) is what we need. I guess we only need an example to demonstrate how to integrate PenaltyFunction.jl with DiffEqParamEstim. @ChrisRackauckas and @finmod examples, please :open_mouth:

**Comment by ChrisRackauckas** [comment]
Don't mix the issues. Use another issue to talk about other forms of regularization.

**Comment by ChrisRackauckas** [comment]
Another thing to note here is that additive noise with `sigma dW_t` as the noise term naturally corresponds to the `N(yhat,sigma)` likelihood function in https://github.com/JuliaDiffEq/DiffEqParamEstim.jl/issues/39 . This would be more computationally expensive though.

**Comment by ChrisRackauckas** [comment]
This does work. Not much else to do here.
