### ISSUE TITLE
Add Tikhonov regularization term to cost function in build_loss_objective function

### ISSUE THREAD

**Issue by Ayush-iitkgp** [JuliaDiffEq/DiffEqParamEstim.jl#33]
As mentioned in Robust and efficient parameter estimation paper. Regularization is used to surmount ill-posedness and ill-conditioning of the problem. `MahalanobisPenalty` from [PenaltyFunctions.jl](https://github.com/JuliaML/PenaltyFunctions.jl) already offers this functionality. The only thing that is needed to be done is show the use case with an example and add docs. I am looking for examples with regard to differential equations where this technique is useful.

**Comment by ChrisRackauckas** [comment]
```julia
p = MahalanobisPenalty(C)
value(p, x)
```

That should evaluate it on `x`.

**Comment by Ayush-iitkgp** [comment]
```
penalty = MahalanobisPenalty(W)
regularization_term = value(penalty,p) # p is the unknown parameter of DE 
regularized_cost_function = non_regularized_cost_function + regularization_term
```
I think the above code would work and return the cost_function to be optimized by different optimizers.

**Comment by ChrisRackauckas** [comment]
You probably want a lambda in there to scale the regularization term?

**Comment by Ayush-iitkgp** [comment]
Oh! yes. Any use case you have in mind? Looks easy to implement. I will make a PR as soon as we have an use case.

**Comment by ChrisRackauckas** [comment]
Use case as in test case? AMIGO2 uses Fitzhugh-Nagumo for this. 

https://sites.google.com/site/amigo2toolbox/examples

For everything, our 3 simple tests should be:

1) Lotka-Volterra
2) Fitzhugh-Nagumo
3) Hogskin-Huxley

Those are classic models every systems biologist would know, and are relatively sane, making them good test cases. Then of course benchmark on larger systems, but those 3 are good small cases.

**Comment by Ayush-iitkgp** [comment]
Should be closed?

**Comment by ChrisRackauckas** [comment]
Yes.
