### ISSUE TITLE
Generalized likelihood function approaches using Distributions.jl

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqParamEstim.jl#39]
Requires the ability to calculate using a user's likelihood function. We would want https://github.com/JuliaStats/Distributions.jl/issues/646 for this.

**Comment by ChrisRackauckas** [comment]
The approach can be as follows:

1) We take in a distribution `d` from the user.
2) From the DiffEq on the parameters, `X` is generated. On that, `dtilde = fit(d,X)` gives the fitted likelihood function at a timepoint.
3) The log-likelihood is then checked against the data `Y` using `loglikelihood(dtilde,Y)`.
4) Optimization repeats this to minimize the loglikelihood. 

Now, to get the likelihood estimates you need multiple samples at a data point. This means that this method isn't useful for ODEs. That makes sense, and in the ODE case we prescribe the `sigma` for the normal likelihood because we don't have it. But for SDEs, we can run a Monte Carlo simulation and get multiple data points at each timepoint and do this full procedure, making use of the stochastic term exactly in the likelihood instead of doing a method of moments approach.

**Comment by Ayush-iitkgp** [comment]
I think we don't need step 2 (remember that it's the user who has to input the covariance of the population). 
```

using Distributions
cost_function = function (p)
    tmp_prob = prob_generator(prob,p)  
    sol = solve(tmp_prob,alg;kwargs...)
    loglikelihood(Normal(0,covariance), sol)  # I think we need to modify a little here.
end
```

**Comment by ChrisRackauckas** [comment]
That only works for `Normal` likelihoods. In general likelihoods, how would we get the parameters? Even if we make the assumption `sol == mean of distribution`, we'd have to account for the the other sufficient statistics in the distribution somehow. For `Normal` it's lucky that it just means the measurement noise can be supplied, but this gets more difficult when it's something like a `Gamma` function. Not sure how to do that kind of stuff in general without doing a full likelihood parameter fitting.

**Comment by ChrisRackauckas** [comment]
http://docs.juliadiffeq.org/latest/analysis/parameter_estimation.html#Generalized-Likelihood-Example-1
