### ISSUE TITLE
Optimizing DDEs

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqParamEstim.jl#46]
With https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/19 the standard loss functions should "just work now", is that right @devmotion? If so, we should get that in a test.

**Comment by devmotion** [comment]
Yes, it works. I just tested the following example:
```julia
using DelayDiffEq, OrdinaryDiffEq, RecursiveArrayTools

function f_lotka(t, u, h, p, du)
    du[1] = 0.5*u[1] - p[1]*u[1]*u[2]
    du[2] = p[2]*h(t-0.5)[1]*u[2] - 0.5*u[2]
end
h = (t) -> [0.5, 0.5]
u0 = [0.5, 0.5]
tspan = (0., 10.)

prob = ConstantLagDDEProblem((t,u,h,du)->f_lotka(t,u,h,[0.5, 1.],du),h,u0,[0.5], tspan)
sol = solve(prob, MethodOfSteps(Tsit5()))

t = collect(linspace(0,10,30))
randomized = VectorOfArray([(sol(t[i]) + .03randn(2)) for i in 1:length(t)])
data = convert(Array, randomized)
```
This gives the following solution and data points:
![lotka_data](https://user-images.githubusercontent.com/26102/28990915-3455ce68-7982-11e7-90e1-f58bec113bc2.png)

Optimization with NLopt
```julia
using DiffEqParamEstim, NLopt

prob_opt = ConstantLagDDEProblem((t,u,h,p,du)->f_lotka(t,u,h,[p[1],1.],du), h, u0, [0.5], tspan)
cost_function = build_loss_objective(prob_opt, MethodOfSteps(Tsit5()),L2Loss(t,data),maxiter=10000)

opt = Opt(:GN_ISRES, 1)
min_objective!(opt, cost_function.cost_function2)
lower_bounds!(opt, [0.0])
upper_bounds!(opt, [1.0])
maxeval!(opt, 10000)
```
gives
```julia
(minf, minx, ret) = NLopt.optimize(opt,[0.2])
(0.34786756604085317, [0.519968], :MAXEVAL_REACHED)
```
which is close to the original value of 0.5. I also plotted this solution:
![lotka_opt](https://user-images.githubusercontent.com/26102/28991140-9c495baa-7984-11e7-9724-2a0891196454.png)

**Comment by ChrisRackauckas** [comment]
hehe `:GN_ISRES` is bad. Yeah, I'll setup some tests and keep this working.

**Comment by ChrisRackauckas** [comment]
It was the tolerances. Lowered them a bit and now it hits 0.500. Thanks.
