### ISSUE TITLE
Pkg.test("DiffEqParamEstim") on master gives error

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqParamEstim.jl#57]
Trying the runtests on master after the latest inclusion of dde gives this error: 

Test Summary: | Error  Total
DDE Tests     |     1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
while loading C:\Users\Denis\.julia\v0.6\DiffEqParamEstim\test\runtests.jl, in expression starting on line 18
==========================[ ERROR: DiffEqParamEstim ]===========================

failed process: Process(`'C:\Users\Denis\AppData\Local\Julia-0.6.1\bin\julia.exe' -Cx86-64 '-JC:\Users\Denis\AppData\Local\Julia-0.6.1\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\Denis\.julia\v0.6\DiffEqParamEstim\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
INFO: Removing Evolutionary v0.1.2
INFO: Removing NLopt v0.3.6
ERROR: DiffEqParamEstim had test errors

**Comment by ChrisRackauckas** [comment]
What's your Pkg.status()? CI shows passing on master, same with me locally. My guess is you have something fixed.

**Comment by ChrisRackauckas** [comment]
Nope, I see what it is. We needed a version bound after the OrdinaryDiffEq release.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaLang/METADATA.jl/pull/11870
