### ISSUE TITLE
Pkg.test("DiffEqParamEstim") fails in out-of-place test

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqParamEstim.jl#59]
....

WARNING: using Distributions.fit in module Main conflicts with an existing identifier.
Test Summary: | Pass  Total
Tests on ODEs |   34     34
106.533243 seconds (300.24 M allocations: 24.020 GiB, 4.86% gc time)
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
WARNING: Interrupted. Larger maxiters is needed.
Test Summary:              | Pass  Total
ParameterizedFunction Type |    1      1
  2.792245 seconds (1.07 M allocations: 61.674 MiB, 0.60% gc time)
WARNING: both NLopt and Optim export "optimize"; uses of it in module Main must be qualified
Out-of-place ODE Tests: Error During Test
  Got an exception of type LoadError outside of a @test
  LoadError: UndefVarError: optimize not defined
  Stacktrace:
   [1] include_from_node1(::String) at .\loading.jl:576
   [2] include(::String) at .\sysimg.jl:14
   [3] macro expansion at C:\Users\Denis\.julia\v0.6\DiffEqParamEstim\test\runtests.jl:18 [inlined]
   [4] macro expansion at .\test.jl:860 [inlined]
   [5] macro expansion at .\util.jl:237 [inlined]
   [6] anonymous at .\<missing>:?
   [7] include_from_node1(::String) at .\loading.jl:576
   [8] include(::String) at .\sysimg.jl:14
   [9] process_options(::Base.JLOptions) at .\client.jl:305
   [10] _start() at .\client.jl:371
  while loading C:\Users\Denis\.julia\v0.6\DiffEqParamEstim\test\out_of_place_odes.jl, in expression starting on line 30
Test Summary:          | Error  Total
Out-of-place ODE Tests |     1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
while loading C:\Users\Denis\.julia\v0.6\DiffEqParamEstim\test\runtests.jl, in expression starting on line 18
==========================[ ERROR: DiffEqParamEstim ]===========================

failed process: Process(`'C:\Users\Denis\AppData\Local\Julia-0.6.1\bin\julia.exe' -Cx86-64 '-JC:\Users\Denis\AppData\Local\Julia-0.6.1\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\Denis\.julia\v0.6\DiffEqParamEstim\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: DiffEqParamEstim had test errors

julia>

**Comment by ChrisRackauckas** [comment]
Yup small test error. Fixed.
