### ISSUE TITLE
Syntax problem with build_lsoptim_ objective

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqParamEstim.jl#65]
In the recent shift to the new syntax, 

cost_function = build_lsoptim_objective(prob,Tsit5(),L2Loss(t,data))

gives the following error:

MethodError: no method matching build_lsoptim_objective(::DiffEqBase.ODEProblem{Array{Float64,1},Float64,true,Array{Float64,1},LorenzExample,Void,Void,UniformScaling{Int64},DiffEqBase.StandardODEProblem}, ::OrdinaryDiffEq.Tsit5, ::DiffEqParamEstim.L2Loss{Array{Float64,1},Array{Float64,2},Void})
Closest candidates are:
  build_lsoptim_objective(::DiffEqBase.DEProblem, ::Any, ::Any, ::Any; prob_generator, kwargs...) at C:\Users\Denis\.julia\v0.6\DiffEqParamEstim\src\build_lsoptim_objective.jl:6

Stacktrace:
 [1] include_string(::String, ::String) at .\loading.jl:522

**Comment by ChrisRackauckas** [comment]
That syntax never changed, you just mixed it up with the `build_loss_objective` function.

```julia
cost_function = build_lsoptim_objective(prob1,t,data,Tsit5())
```

**Comment by finmod** [comment]
Here is the one given in the Parameter estimation Docs:

To solve it using LeastSquaresOptim.jl, we use the build_lsoptim_objective function:

cost_function = build_lsoptim_objective(prob,Tsit5(),L2Loss(t,data))
The result is a cost function which can be used with LeastSquaresOptim. For more details, consult the documentation for LeastSquaresOptim.jl:

**Comment by ChrisRackauckas** [comment]
That's an error in the docs. Thanks.

**Comment by finmod** [comment]
There is still more than one problem with this Docs page and LeastSquaresOptim.

First, prob1 instead of prob in: cost_function = build_lsoptim_objective(prob1,t,data,Tsit5())

Then, x = [1.3,0.8,2.8,1.2]
res = optimize!(LeastSquaresProblem(x = x, f! = cost_function,
                output_length = length(t)*length(prob.u0)),
                LeastSquaresOptim.Dogleg(),LeastSquaresOptim.LSMR(),
                ftol=1e-14,xtol=1e-15,iterations=100,grtol=1e-14)
the syntax has changed toward an input like

res = optimize!(LeastSquaresProblem(x = x, f! = rosenbrock_f!, output_length = 2), LeastSquaresOptim.LSMR())

In addition, Pkg.test("DiffEqParamEstim") fails on the LeastSquaresOptim tests.

**Comment by Vaibhavdixit02** [comment]
I'll be happy to take a stab if it is alright with @finmod.

**Comment by finmod** [comment]
Fine with me. My limited diagnostic is that LeastSquaresOptim has moved to: a simple syntax and an advanced syntax as stated in the README. 
We use the advanced syntax and there our cost_function should have two explicit arguments whereas at present there are none.

**Comment by Vaibhavdixit02** [comment]
Thanks, that will help me :slightly_smiling_face:

**Comment by finmod** [comment]
@Vaibhavdixit02 and @ChrisRackauckas Looking at the notebooks that you publish on DiffeEqBenchmarks I suggest that the call to BlackBoxOptim be as follows:

obj = build_loss_objective(prob,Vern9(),L2Loss(t,data),tstops=t,reltol=1e-9,abstol=1e-9)
@time res1 = bboptimize(obj;SearchRange = glo_bounds, MaxSteps = 16e3, TraceMode=:silent)
@show (best_fitness(res1), best_candidate(res1))

This reduces printing of uninformative material and puts the output on an equal footing with other optimizers. It may still be one line too many if you can find a way to simplify it further.

The conclusions should be sharper to say that BBO is the only game in town until perhaps QuadDIRECT comes along. The comparisons should take place only with other global optimizers in NLopt i.e. the GN and GD classes of NLopt. Finally BBO is 100% Julia with no need to go via MatProgBase and it does include some of the GN algorithms as non-default. One caveat is that BBO may need a restart option to check that the random initial values do not derail the optimization. This happens rarely in my experience.

**Comment by ChrisRackauckas** [comment]
>The comparisons should take place only with other global optimizers in NLopt i.e. the GN and GD classes of NLopt.

I disagree. I have had too many people try to tell me local optimizers are fine for this. I want proof that they are usually not.

>The conclusions should be sharper to say that BBO is the only game in town until perhaps QuadDIRECT comes along. 

In the newer benchmarks @Vaibhavdixit02 found places for BBO failed and NLopt succeeded. If you think you know why, please submit a PR updating the notebooks. He tried QuadDIRECT.jl as well and it didn't seem to do well. Also, the DIRECT method from NLopt doesn't seem to do well too, so it might be a method thing.

**Comment by Vaibhavdixit02** [comment]
The syntax for `optimize!` seems to have changed and it doesn't support the kwargs `ftol` `xtol` `iterations` `grtol` anymore as @finmod mentioned, the problem was arising because of a part in the `build_lsoptim_objective` which was meant to ensure the same length of the two arrays was actually doing the opposite of what it should have been doing.

**Comment by ChrisRackauckas** [comment]
Completed.

**Comment by finmod** [comment]
"In the newer benchmarks @Vaibhavdixit02 found places for BBO failed and NLopt succeeded. If you think you know why, please submit a PR updating the notebooks." 

I would be surprised at that. Back to my initial suggestion to present the optimization:

obj = build_loss_objective(prob,Vern9(),L2Loss(t,data),tstops=t,reltol=1e-9,abstol=1e-9)
@time res1 = bboptimize(obj;SearchRange = glo_bounds, MaxSteps = 16e3, TraceMode=:silent)
@show (best_fitness(res1), best_candidate(res1))

and use MaxSteps to give BBO a chance to reach either best_fitness or best_candidates. MaxSteps = 4e3, used in the notebooks is way too small for larger optimization.

**Comment by ChrisRackauckas** [comment]
I would appreciate a PR from you or @Vaibhavdixit02 demonstrating that. Easiest way to show the benchmark is wrong is to fix it 👍
