### ISSUE TITLE
2 Stage Method: Row-Order and Requires Vector Problem

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqParamEstim.jl#9]
The lines:

```julia
    estimated_solution = zeros(n,size(data)[2])
    estimated_derivative = zeros(n,size(data)[2])
```

assume that the problem is a vector. This causes an issue if the `u0` is supposed to be a matrix. Also, this leads to further code using:

```julia
estimated_solution[i,:]
```

This isn't good because Julia is column-major. A better solution would be for 

```julia
    estimated_solution = Vector{typeof(prob.u0)}(n)
    estimated_derivative = Vector{typeof(prob.u0)}(n)
```

Then it would be `estimated_solution[i]` everywhere. The only issue is typing the returns from the estimates. It's not exactly clear how to re-write

```julia
        estimated_solution[i,:] = e1'*inv(T1'*W*T1)*T1'*W*data
        estimated_derivative[i,:] = e2'*inv(T2'*W*T2)T2'*W*data
```

to work for `data` which is 1+N dimensional instead of `1+1` dimension (1 for vector).

**Comment by Ayush-iitkgp** [comment]
@ChrisRackauckas any sample ODE where the above conditions hold would be appreciated.

**Comment by ChrisRackauckas** [comment]
The ParameterizedFunctions.jl macros cannot make a non-vector equation, so that's good at least. But generic ParameterizedFunctions can be made from the constructor. Real cases come from discretizations of PDEs. For a test case, I use a variation of this sometimes:

```julia
f_2dlinear = (t,u,p,du) -> begin
  for i in 1:length(u)
    du[i] = p*u[i]
  end
end
pf = ParameterizedFunction(f,1.01)
prob_ode_2Dlinear = ODEProblem(f_2dlinear,rand(4,2))
```

This is a 4x2 linear ODE with growth rate which is the parameter, which is set as `p=1.01`. Each timestep is a 4x2 matrix. The data would be 4x2 matrices over time, which you could represent as a 3-tensor.

Now that I think about it, the `vecvec_to_mat` strategy for the reduction (which is also used in the other methods) might have trouble with this. The reductions might need to be more sophisticated.

**Comment by ChrisRackauckas** [comment]
The easiest way to solve this would be to probably reinterpret the tensor equations as a vector equation by its linear index. Then, `reshape` when necessary. Even if this is done, you want to change to `estimated_solution[:,i]` since that'll be faster (column-order!)
