### ISSUE TITLE
Chaining the optimizers

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqParamEstim.jl#99]
@ChrisRackauckas @Vaibhavdixit02 I just noticed in BlackBoxOptimBenchmarking of JonathanBieler that he has now rolled the global/local optimiziation issue into one by chaining various global candidates with the various local candidates plus a weight to switch for the most efficient overall optimization.

This could greatly simplify the Parameter Estimation docs and examples as the best outcome is the tuple: standard BBO, Optim NelderMead.

The chain function can be found here:  https://github.com/jonathanBieler/BlackBoxOptimizationBenchmarking.jl/blob/master/scripts/optimizers_interface.jl

**Comment by ChrisRackauckas** [comment]
Yes, chaining should be used with pretty much any global optimization. I'm not sure how much we should document that though since that's a topic for optimization docs. Our docs are getting pretty full on this topic already, and we need more time spent on building the objectives.

**Comment by ChrisRackauckas** [comment]
This is a user-side thing. Maybe a tutorial thing, but not a dev thing.
